### ISSUE TITLE
v0.9.0 broke my CI , needed to revert to 0.8.4

### ISSUE THREAD

**Issue by joaomcteixeira** [tox-dev/tox-conda#117] opened 2021-12-17 14:14 UTC
Hi folks,
First of all, thanks so much for your amazing software.

Today, I got completely puzzled because my CI stop working with tox giving me this error:

`/tmp/tmpo4js6lp2: 1: export: .: bad variable name` , you can see it [here](https://github.com/joaomcteixeira/taurenmd/runs/4560478421?check_suite_focus=true) in the github actions.

I needed to go dep by dep looking for which one of it had been updated in the last week because everything was working until some days ago. Finally, I found `tox-conda` had been updated during these days to 0.9.0.

This [commit](https://github.com/joaomcteixeira/taurenmd/tree/3100ca8f68f9761de4e242f1ea17aa1122c51944) was working 6 days ago.

I am now merging [this PR](https://github.com/joaomcteixeira/taurenmd/pull/60)

to reproduce the error:

```
# clone the repo
conda create --name sometestenv python=3.9 pip setuptools wheel tox=3.24.4
tox -e py39
```

After that, you can change the line in `tox.ini` removing the version number
`requires=tox-conda==0.8.4` to `requires=tox-conda`

Hope this helps,
Cheers,

**Comment by AntoineD** [comment] 2021-12-19 21:20
Duplicate of #115.

**Closed by AntoineD** 2021-12-19 21:20 UTC
