### ISSUE TITLE
Crash in testenv creation

### ISSUE THREAD

**Issue by linus-gates** [tox-dev/tox-conda#56] opened 2020-11-18 07:25 UTC
The line:
`del venv.envconfig.config.interpreters.name2executable[venv.name]`
gives keyError: py38 
(py38 is my tox env name).

running on linux, python3.8, inside a conda environment.

**Comment by AntoineD** [comment] 2020-11-19 08:10
Could you describe the context of this issue such that it could be reproduced?

**Comment by JarnoRFB** [comment] 2020-11-27 08:16
I experience the same error after upgrading to `0.4.1`. The code was introduced in https://github.com/tox-dev/tox-conda/pull/52 I guess. 

My tox.ini looks like this 

```
[tox]
envlist =
    py36

[testenv]
commands =
    pytest \
        -s \
        -m "not plot and not integration" \
        {posargs}
deps =
    pytest >= 3.8,<4


[testenv:integration]
commands =
 pytest \
     -m "gpu or integration" \
     {posargs}
deps =
    pytest >= 3.8,<4
```

Most details here are probably not so important, but the same tox.ini used to work with `0.2.1`. I call tox in my build scripts with something like
`tox--installpkg "${cfg.distLocation}*.tar.gz --workdir cfg.tox.workingDirectory -c toxIni.unsafeEncode`.

Maybe this helps in locating the source of the problem. Otherwise we would need to figure out a more minimal reproduction of the problem.

**Comment by AntoineD** [comment] 2020-11-27 08:46
Hi @JarnoRFB,

as @linus-gates mentioned, there is a weak spot that I introduced in a recent commit, but I'd like to understand what is the situation that triggers this bug so we can get the root cause.

Is it reproducible even after deleting your .tox directory?

**Comment by domeniconappo** [comment] 2021-03-25 16:32
Hi everyone,

any reason why the commit is not merged yet?
I've tried and it works :)

**Comment by AntoineD** [comment] 2021-03-25 16:37
Hi @domeniconappo,
I was just waiting for an answer before going further with a PR.

**Comment by JarnoRFB** [comment] 2021-03-26 08:52
Really sorry I didn't get around to testing this, but if it works for other people don't let it get blocked by me.

**Closed** 2021-04-02 23:14 UTC
