### ISSUE TITLE
Environment not activated correctly (basemap)

### ISSUE THREAD

**Issue by aperezhortal** [tox-dev/tox-conda#29] opened 2019-07-31 20:03 UTC
I'm trying to use tox-conda to create an environment with Basemaps on it but it fails set the environment variables during the initialization of the environment. 

More in detail, the PROJ_LIB is not set during the initialization. This is the minimal example that show the possible bug:
  
```
[tox]
envlist = py36
skipsdist=True

[testenv]
conda_deps=
    basemap

conda_channels=
    conda-forge
    default

commands =
    python -c "from mpl_toolkits.basemap import Basemap"
```

Error on running `tox -v `:
```
<...>/.tox/py36/bin/python -c 'from mpl_toolkits.basemap import Basemap'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<...>./.tox/py36/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py", line 155, in <module>
    pyproj_datadir = os.environ['PROJ_LIB']
  File "<...>./.tox/py36/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'PROJ_LIB'
```

**Comment by aperezhortal** [comment] 2019-08-01 17:44
A possible workaround for this particular case is adding setting the environment variable in tox.ini 
```
setenv = PROJ_LIB={envdir}/share/proj
```

**Comment by QuLogic** [comment] 2019-12-02 07:26
I think this is a duplicate of #24 (which I also don't think is platform-specific.)

**Closed** 2020-11-08 17:31 UTC
Labels: pr-available
